name: Upload NuGet package

on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/leonverschuren/index.json
      - run: dotnet build --configuration Release TestExtensions
      - name: Create the package
        run: dotnet pack --no-build --configuration Release TestExtensions -p:PackageVersion=${{ github.event.release.tag_name }}
      - name: Publish the package to GPR
        run: dotnet nuget push TestExtensions/bin/Release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}}
